[entryPoints]
    [entryPoints.web]
        address = ":80"
    [entryPoints.web.http]
        [entryPoints.web.http.redirections]
            [entryPoints.web.http.redirections.entryPoints]
                to = "websecure"
                scheme = "https"
    [entryPoints.websecure]
        address = ":443"

[accessLog]

[api]
dashboard = true

[providers]
    [providers.docker]
        exposeByDefault = false

[certificatesResolvers.letsencrypt.acme]
    email = "moz5691@gmail.com"
    storage = "/certificates/acme.json"
    [certificatesResolvers.letsencrypt.acme.httpChallenge]
        entryPoint = "web"